"""adds 

Revision ID: 3cf4b04f1764
Revises: 55ebe6541ca6
Create Date: 2019-06-06 11:35:42.839021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf4b04f1764'
down_revision = '55ebe6541ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('other2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'other2')
    # ### end Alembic commands ###
